---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-frame-plume-labs-io-v1beta1-framejob
  failurePolicy: Fail
  name: mframejob-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - framejobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-frame-plume-labs-io-v1beta1-framenode
  failurePolicy: Fail
  name: mframenode-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - framenodes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-framejob
  failurePolicy: Fail
  name: vframejob-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - framejobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-framenode
  failurePolicy: Fail
  name: vframenode-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - framenodes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-frameresourcequota
  failurePolicy: Fail
  name: vframeresourcequota-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frameresourcequotas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-services-plume-labs-io-v1beta1-frameservice
  failurePolicy: Fail
  name: vframeservice-v1beta1.kb.io
  rules:
  - apiGroups:
    - services.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - frameservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-frameuser
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vframeuser-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - frameusers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-schedulingpolicy
  failurePolicy: Fail
  name: vschedulingpolicy-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - schedulingpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-talosmachineconfig
  failurePolicy: Fail
  name: vtalosmachineconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - talosmachineconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frame-plume-labs-io-v1beta1-talosupgrade
  failurePolicy: Fail
  name: vtalosupgrade-v1beta1.kb.io
  rules:
  - apiGroups:
    - frame.plume-labs.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - talosupgrades
  sideEffects: None
