{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frame.name" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frame.chartLabels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "frame.selectorLabels" . | nindent 4 }}
{{- end }}
