apiVersion: frame.plume-labs.io/v1alpha1
kind: TalosUpgrade
metadata:
  labels:
    app.kubernetes.io/name: frame
    app.kubernetes.io/managed-by: kustomize
  name: worker-01-upgrade
  namespace: frame-system
spec:
  nodeName: worker-01
  talosEndpoint: "192.168.10.10:50000"
  talosSecretRef:
    name: talos-client-certs
    namespace: frame-system
  image: ghcr.io/siderolabs/talos:v1.9.0
