apiVersion: frame.plume-labs.io/v1alpha1
kind: FrameResourceQuota
metadata:
  labels:
    app.kubernetes.io/name: frame
    app.kubernetes.io/managed-by: kustomize
  name: frameresourcequota-sample
spec:
  # TODO(user): Add fields here
