## Append samples of your project ##
resources:
- frame_v1beta1_framenode.yaml
- frame_v1beta1_framejob.yaml
- frame_v1beta1_schedulingpolicy.yaml
- frame_v1beta1_frameresourcequota.yaml
- frame_v1beta1_talosmachineconfig.yaml
- frame_v1beta1_talosupgrade.yaml
- frame_v1beta1_frameuser.yaml
- services_v1beta1_frameservice.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
