apiVersion: services.plume-labs.io/v1alpha1
kind: FrameService
metadata:
  labels:
    app.kubernetes.io/name: frame
    app.kubernetes.io/managed-by: kustomize
  name: frameservice-sample
spec:
  # TODO(user): Add fields here
