apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-control-ingress
  namespace: cluster-control
spec:
  tls:
    - hosts:
        - frame.REPLACE_YOUR_DOMAIN
      secretName: cluster-control-prod-tls
  rules:
    - host: frame.REPLACE_YOUR_DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-control-ui
                port:
                  name: http
