---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: neura-alert-webhook
  namespace: monitoring
spec:
  encryptedData:
    token: AgBd4QYMBvMpOUKS6vxb6J48Ao+w+6bvG6qLYztmcvuufNH37D7q2qhQQhrPZkRQiE/o54VkclunLh0W0fBMEzKLrWCLFDw6rzTCoTYuy0OeVLIXuGTIsdvfbc4EvSMQf44p8HTY2CXFtf16sLshPe6/WzjNeVa+1HceM+zoB9kFGbFFq4hVMlD8kJqhIxD1pjjZhCUmOohZ08QYkF6DaRd60REpVWrehK7BEwA9AeSMCZXEEnFstkfZxQmhFbEXazHMbU5949KsHRtfr1H7fPmEGTNK7ChVfa3+3JrX9HelD3DoYknX8JtZ6axTfNJdcFIFqgwHYAjVWZGx1AQlQ3NYnTbWXgZ9kKEAAu3t9s+k5YPeoAOLDh2xdmI3mWQtByQfChlRbKLtU7SdvA2JwfvkRuszHSwLnxqdirXhTPhRR55TPLjMfIJ5QKVwbSXvkjcO9OsLRtWLiQfCldEEYNe55GlL5cDy/yDtyGKliB1rlXWJXOWXSfFaa+7mnYnNvL4XvChdsNIwDR/2i1tAVBln4l7gOj4XAY8dBMSBGk7NAO4/1ENteSwXUw6orEyZ+lSCnddhZTtiuD7/moaiOtNUfRyTkkUwF2kDmPzI4fXi7zXf/bwbM3nLrmuBYAGK58R5r+lrynm4qvFNsqVQ2ywvCyLreyyO4x003RqvYFw5AVXaRZHyFcbhSG2OIoN5rOyozm8J8txVBT9Onx6pa4n1WfRDtotXVbCN69AkF3m2891BS4ptZY0Bld7ynfkaewB6/JuEU9muw6c4p1ndtUih
  template:
    metadata:
      name: neura-alert-webhook
      namespace: monitoring
