apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-infrastructure
  namespace: argocd
spec:
  description: Bare metal cluster infrastructure and monitoring
  sourceRepos:
    - 'https://github.com/Plume-Labs/frame.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
