package provision

import (
	"fmt"
	"net"
	"strings"
	"text/template"

	"golang.org/x/crypto/ssh"
)

// markerPath is where the installed system records which installation produced
// it. Frame reads it over SSH before believing the machine is its own.
const markerPath = "/etc/frame-install-uid"

const preseedTemplate = `# Generated by Frame. Do not edit on the machine.
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

d-i netcfg/choose_interface select auto
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/get_ipaddress string {{ .IP }}
d-i netcfg/get_netmask string {{ .Netmask }}
d-i netcfg/get_gateway string {{ .Gateway }}
d-i netcfg/get_nameservers string {{ .DNS }}
d-i netcfg/confirm_static boolean true
d-i netcfg/get_hostname string {{ .Hostname }}
d-i netcfg/get_domain string local
d-i netcfg/hostname string {{ .Hostname }}

d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string

d-i passwd/root-login boolean false
d-i passwd/user-fullname string Frame
d-i passwd/username string frame
d-i passwd/user-password-crypted password !
d-i user-setup/allow-password-weak boolean false
d-i user-setup/encrypt-home boolean false

d-i clock-setup/utc boolean true
d-i time/zone string Etc/UTC
d-i clock-setup/ntp boolean true

# Refuse before partman touches anything if a named disk is not the size Frame
# was told it is. Frame checked the machine's serial remotely; this checks its
# disks locally. Both can be wrong, but not in the same way.
d-i preseed/early_command string {{ .SizeAssertion }} || { echo "FRAME: named disk is not the expected size, refusing" >&2; exit 1; }

{{ .Partman }}
tasksel tasksel/first multiselect standard, ssh-server
d-i pkgsel/include string openssh-server sudo ca-certificates curl
d-i pkgsel/upgrade select none
popularity-contest popularity-contest/participate boolean false

d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean false
d-i finish-install/reboot_in_progress note

d-i preseed/late_command string \
  in-target mkdir -p /home/frame/.ssh ; \
  echo '{{ .SSHPublicKey }}' > /target/home/frame/.ssh/authorized_keys ; \
  in-target chown -R frame:frame /home/frame/.ssh ; \
  in-target chmod 700 /home/frame/.ssh ; \
  in-target chmod 600 /home/frame/.ssh/authorized_keys ; \
  echo 'frame ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/frame ; \
  in-target chmod 440 /etc/sudoers.d/frame ; \
  echo '{{ .UID }}' > /target{{ .MarkerPath }} ; \
  in-target chmod 444 {{ .MarkerPath }}
`

// RenderPreseed turns a Spec into a preseed.cfg.
//
// It refuses rather than emits when something is wrong, because the two ways
// this can go badly are silent: an image carrying secret material, and an
// installation that wipes a disk nobody named.
func RenderPreseed(s Spec) (string, error) {
	if strings.TrimSpace(s.UID) == "" {
		return "", fmt.Errorf("spec: UID is empty, so the installed system could not be told apart from any other machine at that address")
	}
	if strings.TrimSpace(s.Hostname) == "" {
		return "", fmt.Errorf("spec: hostname is empty")
	}
	if err := checkPublicKeyOnly(s.SSHPublicKey); err != nil {
		return "", err
	}

	ip, ipnet, err := net.ParseCIDR(s.Network.Address)
	if err != nil {
		return "", fmt.Errorf("network address %q: %w", s.Network.Address, err)
	}
	if net.ParseIP(s.Network.Gateway) == nil {
		return "", fmt.Errorf("network gateway %q is not an IP address", s.Network.Gateway)
	}

	partman, err := PartmanRecipe(s.Layout)
	if err != nil {
		return "", err
	}

	data := struct {
		IP, Netmask, Gateway, DNS, Hostname string
		SizeAssertion, Partman              string
		SSHPublicKey, UID, MarkerPath       string
	}{
		IP:            ip.String(),
		Netmask:       net.IP(ipnet.Mask).String(),
		Gateway:       s.Network.Gateway,
		DNS:           strings.Join(s.Network.DNS, " "),
		Hostname:      s.Hostname,
		SizeAssertion: diskSizeAssertion(s.Layout),
		Partman:       partman,
		SSHPublicKey:  strings.TrimSpace(s.SSHPublicKey),
		UID:           s.UID,
		MarkerPath:    markerPath,
	}

	var b strings.Builder
	if err := template.Must(template.New("preseed").Parse(preseedTemplate)).Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// checkPublicKeyOnly is the guard that keeps decision 3 true. The image is
// served over an unauthenticated HTTP path reachable by every notebook and
// sandbox on the platform, so anything secret in it is published.
//
// ssh.ParseAuthorizedKey is not that guard, and believing it was is the trap
// here. Handed a whole key file it finds the public line, ignores the private
// one, and returns no error -- measured, in both orders. So a Secret whose
// "id.pub" actually holds both halves, or a paste of `cat id_ed25519*`, parses
// cleanly and would be written into the image verbatim.
//
// What closes it is the single-line rule: one key, on one line, and nothing
// else in the value.
func checkPublicKeyOnly(key string) error {
	k := strings.TrimSpace(key)

	// A boundary this value crosses twice: into a generated preseed, and from
	// there onto a machine's disk. An ed25519 line is about 100 characters and
	// an RSA-4096 one about 750; 1024 admits both and refuses a paste of
	// something else entirely.
	if len(k) == 0 || len(k) > 1024 {
		return fmt.Errorf("ssh key: must be between 1 and 1024 characters, got %d", len(k))
	}

	// This branch is for the message, not for the hole -- the single-line rule
	// below already refuses every multi-line value. But "this is private key
	// material" is worth far more to whoever hit it than "must be a single
	// line", so its test asserts the message rather than merely the error.
	if strings.Contains(k, "PRIVATE KEY") {
		return fmt.Errorf("ssh key: this is private key material, which must never enter an installer image")
	}
	// This rule is not mainly about secrets -- the branch above catches PEM
	// armour, and a private key without armour is not a shape anyone produces
	// by accident. Its job is the other two: a second line is a second
	// authorized key, which grants someone else access to the machine being
	// built, and a newline inside the value truncates the shell command that
	// writes it in the preseed.
	if strings.ContainsAny(k, "\n\r") {
		return fmt.Errorf("ssh key: must be one key on one line; a second line is a second key, and a newline truncates the command that writes this value")
	}
	// The value is interpolated into a single-quoted shell word in the
	// preseed's late_command. A quote or a backslash in the comment field
	// breaks out of it, which turns a key comment into arbitrary commands run
	// as root on the machine being installed.
	if strings.ContainsAny(k, "'\\") {
		return fmt.Errorf("ssh key: must not contain a quote or a backslash; this value is interpolated into a shell command in the preseed")
	}

	_, comment, _, _, err := ssh.ParseAuthorizedKey([]byte(k))
	if err != nil {
		return fmt.Errorf("ssh key: not a usable authorized_keys line: %w", err)
	}
	// The parser's trailing remainder is not the check it looks like: it holds
	// unconsumed *lines*, never unconsumed words, and the single-line rule
	// above already refuses every multi-line value -- so inspecting it would
	// be dead code behind a passing test. Two keys on one line land somewhere
	// else entirely: the parser takes the first and folds the whole second key
	// into the first one's comment field. Measured. So the comment is what has
	// to be looked at, and the exact test is whether it parses as a key on its
	// own.
	if _, _, _, _, err := ssh.ParseAuthorizedKey([]byte(strings.TrimSpace(comment))); err == nil {
		return fmt.Errorf("ssh key: more than one key in this value; the second is hidden in the first one's comment field")
	}
	return nil
}
