package provision

import (
	"fmt"
	"net"
	"strings"
	"text/template"
	"unicode/utf8"

	"golang.org/x/crypto/ssh"
)

// markerPath is where the installed system records which installation produced
// it. Frame reads it over SSH before believing the machine is its own.
const markerPath = "/etc/frame-install-uid"

// NetcfgRerunScript is what preseed/run points at, and it is the whole
// reason the static-network block below is not decoration.
//
// Debian states the constraint outright: "preseeding the network
// configuration won't work if you're loading your preconfiguration file
// from the network". netcfg has to bring the machine online BEFORE the
// preseed can be fetched at all -- which is precisely why url= worked on
// the ML350 Gen9 where file=/cdrom/preseed.cfg did not. So by the time any
// netcfg/* answer in this file is loaded, netcfg has already run, over
// DHCP, and every one of those answers only suppresses a question that is
// never asked again. On its own the block configures nothing: the machine
// installs, reboots, and comes up on whatever address DHCP handed it,
// under whatever name DHCP handed it -- at which point Frame waits for a
// machine at an address nobody is on, and times out having already wiped
// both disks.
//
// Debian documents the workaround in the same appendix, and this is it
// verbatim: a preseed/run script that kills the DHCP client and runs
// netcfg a second time, when the answers are already in the debconf
// database.
//
// UNPROVEN ON HARDWARE. That this re-run actually takes the static address
// has not been observed on a machine -- it joins the not-yet-executed list
// beside "the image boots", "partman partitions" and "k3s joins". What is
// proven here is only what can be: that the rendered preseed carries the
// directive, and that the script the directive names is served.
//
// `netcfg-done` is emitted AFTER the `netcfg` command returns, not beside
// the `netcfg` checkpoint above it. That is the whole discriminator finding
// 3 exists for: `netcfg` alone is emitted at the TOP of this script, before
// kill-all-dhcp, so its presence with nothing past it covers everything
// between there and the disk-size guard -- above all a netcfg re-run that
// never takes the static address, which is exactly the UNPROVEN case this
// comment names. A machine that reaches `netcfg-done` has proven the
// re-run worked; one that reaches the guard and is refused there will have
// sent both `netcfg` and `netcfg-done`, but never `early`.
const runScriptTemplate = `#!/bin/sh
# Generated by Frame. Do not edit on the machine.
#
# Debian's documented workaround for network-fetched preseeds: force the
# network configuration to run again now that the preconfiguration file has
# been loaded. Without this the static address above is never applied.
{{ if .Beacon }}{{ .Beacon }}
{{ end }}kill-all-dhcp
netcfg
{{ if .BeaconDone }}{{ .BeaconDone }}
{{ end }}`

var runScriptTmpl = template.Must(template.New("runscript").Parse(runScriptTemplate))

// RenderRunScript produces the preseed/run script, optionally reporting the
// netcfg and netcfg-done checkpoints around its work.
//
// The first beacon goes BEFORE kill-all-dhcp: this script is about to tear
// the DHCP lease down and bring the interface back on a static address, and
// a report sent after that is a report that may never leave. Reaching this
// script at all is what `netcfg` means as a checkpoint. The second goes
// AFTER netcfg returns, so `netcfg-done` means what its name says: the
// re-run happened and the interface is (as far as this shell can tell)
// back up -- see the const's own comment for why that is the discriminator
// finding 3 needs.
func RenderRunScript(beaconBase, token string) string {
	var b strings.Builder
	// The template has no failure mode a caller can trigger: both fields are
	// strings this package produced, and Execute on a parsed template with a
	// struct of strings cannot fail. Errors are therefore not returned --
	// there is no caller decision to make about one.
	_ = runScriptTmpl.Execute(&b, struct{ Beacon, BeaconDone string }{
		Beacon:     BeaconSend(beaconBase, token, CheckpointNetcfg),
		BeaconDone: BeaconSend(beaconBase, token, CheckpointNetcfgDone),
	})
	return b.String()
}

const preseedTemplate = `# Generated by Frame. Do not edit on the machine.
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

d-i netcfg/choose_interface select auto
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/get_ipaddress string {{ .IP }}
d-i netcfg/get_netmask string {{ .Netmask }}
d-i netcfg/get_gateway string {{ .Gateway }}
d-i netcfg/get_nameservers string {{ .DNS }}
d-i netcfg/confirm_static boolean true
d-i netcfg/get_hostname string {{ .Hostname }}
d-i netcfg/get_domain string local
# netcfg/hostname is the force knob, not netcfg/get_hostname: Debian notes
# that "any hostname and domain names assigned from dhcp take precedence
# over values set here", and get_hostname is one of the values it means.
# netcfg/hostname is documented as forcing a hostname "regardless of what
# either the DHCP server returns or what the reverse DNS entry for the IP
# is". Both are set -- get_hostname to suppress the question, hostname to
# decide the answer.
d-i netcfg/hostname string {{ .Hostname }}

# Everything above is inert on its own: see RenderRunScript. This is the
# directive that makes it live -- d-i runs this script right after loading
# this file, and the script re-runs netcfg against the answers above.
d-i preseed/run string {{ .RunURL }}

d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string

d-i passwd/root-login boolean false
d-i passwd/user-fullname string Frame
d-i passwd/username string frame
d-i passwd/user-password-crypted password !
d-i user-setup/allow-password-weak boolean false
d-i user-setup/encrypt-home boolean false

d-i clock-setup/utc boolean true
d-i time/zone string Etc/UTC
d-i clock-setup/ntp boolean true

# Refuse before partman touches anything if a named disk is not the size Frame
# was told it is. Frame checked the machine's serial remotely; this checks its
# disks locally. Both can be wrong, but not in the same way.
#
# This does not depend on a non-zero early_command aborting the install --
# that behaviour could not be verified here. It powers the machine off
# directly instead: an untouched, powered-off machine is a safe failure, and
# Frame's Installing phase times out and reports it.
#
# Written as if/then/else, not "ASSERT || { ...; poweroff -f; } ; EARLY ;
# HEARTBEAT": a trailing semicolon after the { } group runs regardless of
# which side of || fired, so on a refused machine the beacon calls would
# still run -- reporting "early" for a machine the guard just powered off,
# unless poweroff -f's reboot(RB_POWER_OFF) never returns. if/then/else
# does not depend on that: the beacon calls are reachable only through the
# branch that runs when the assertion passed.
d-i preseed/early_command string if {{ .SizeAssertion }}; then {{ if .BeaconEarly }}{{ .BeaconEarly }} ; {{ .BeaconHeartbeat }}{{ else }}:{{ end }}; else echo "FRAME: named disk is not the expected size, refusing" > /dev/console; poweroff -f; fi

{{ .Partman }}
{{ if .BeaconPartman }}d-i partman/early_command string {{ .BeaconPartman }}
{{ end }}
tasksel tasksel/first multiselect standard, ssh-server
d-i pkgsel/include string openssh-server sudo ca-certificates curl
d-i pkgsel/upgrade select none
popularity-contest popularity-contest/participate boolean false

d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean false
d-i finish-install/reboot_in_progress note

d-i preseed/late_command string \
  in-target mkdir -p /home/frame/.ssh ; \
  echo '{{ .SSHPublicKey }}' > /target/home/frame/.ssh/authorized_keys ; \
  in-target chown -R frame:frame /home/frame/.ssh ; \
  in-target chmod 700 /home/frame/.ssh ; \
  in-target chmod 600 /home/frame/.ssh/authorized_keys ; \
  echo 'frame ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/frame ; \
  in-target chmod 440 /etc/sudoers.d/frame ; \
  echo '{{ .UID }}' > /target{{ .MarkerPath }} ; \
  in-target chmod 444 {{ .MarkerPath }} ; \
  echo '{{ .Hostname }}' > /target/etc/hostname ; \
  echo '127.0.1.1 {{ .Hostname }}' >> /target/etc/hosts{{ if .BeaconLate }} ; \
  {{ .BeaconLate }}{{ end }}
`

// Two notes on the last two lines of that late_command, because each is
// load-bearing for a reason the other does not explain:
//
// /etc/hostname is the belt under C1's netcfg re-run -- Debian says a
// DHCP-assigned name takes precedence, and whether the re-run settles the
// name cannot be observed from here.
//
// **The /etc/hosts line is also what keeps `sudo` quiet.** Without an entry
// mapping the machine's own hostname, every sudo invocation prints
// "sudo: unable to resolve host <name>" to stderr while still exiting 0 --
// and Join reads the new cluster's kubeconfig over sudo. join.go does not
// depend on that (it reads stdout only, and refuses a sudo preamble by
// name), but this line is why the common trigger does not arise in the
// first place. Do not remove it as "cosmetic, netcfg sets the hostname":
// it is holding two things up, and only one of them is the hostname.

// preseedTmpl is parsed once at package init so a template typo panics at
// build/test time rather than on the first call to RenderPreseed.
var preseedTmpl = template.Must(template.New("preseed").Parse(preseedTemplate))

// ValidateSpec runs every refusal RenderPreseed makes that depends only on
// the Spec, and none that depend on the URLs a render is given.
//
// It exists so Remaster can refuse a bad Spec before it touches the base
// image without having to invent a run-script URL it has no business
// knowing. RenderPreseed calls it too, so there is one list of refusals,
// not two that drift.
func ValidateSpec(s Spec) error {
	_, _, _, err := renderInputs(s)
	return err
}

// renderInputs validates a Spec and returns the three derived values the
// template needs: the bare address, the netmask, and the partman recipe.
// Validation and derivation are one function because splitting them means
// parsing the address twice and, eventually, parsing it differently.
func renderInputs(s Spec) (ip net.IP, netmask net.IP, partman string, err error) {
	if err := checkPreseedValue("UID", s.UID); err != nil {
		return nil, nil, "", err
	}
	if strings.TrimSpace(s.UID) == "" {
		return nil, nil, "", fmt.Errorf("spec: UID is empty, so the installed system could not be told apart from any other machine at that address")
	}
	if err := checkPreseedValue("hostname", s.Hostname); err != nil {
		return nil, nil, "", err
	}
	if strings.TrimSpace(s.Hostname) == "" {
		return nil, nil, "", fmt.Errorf("spec: hostname is empty")
	}
	if err := checkPublicKeyOnly(s.SSHPublicKey); err != nil {
		return nil, nil, "", err
	}

	if err := checkPreseedValue("network address", s.Network.Address); err != nil {
		return nil, nil, "", err
	}
	addr, ipnet, err := net.ParseCIDR(s.Network.Address)
	if err != nil {
		return nil, nil, "", fmt.Errorf("network address %q: %w", s.Network.Address, err)
	}
	if addr.To4() == nil {
		return nil, nil, "", fmt.Errorf("network address %q: must be IPv4", s.Network.Address)
	}

	if err := checkPreseedValue("network gateway", s.Network.Gateway); err != nil {
		return nil, nil, "", err
	}
	if net.ParseIP(s.Network.Gateway) == nil {
		return nil, nil, "", fmt.Errorf("network gateway %q is not an IP address", s.Network.Gateway)
	}

	// An empty resolver list is refused, not defaulted. It rendered
	// "d-i netcfg/get_nameservers string " -- empty -- against a mirror
	// named deb.debian.org, and partman runs BEFORE the base system is
	// fetched: the install halts at critical priority asking a question
	// nobody is there to answer, after both disks are already gone, and
	// Frame sees only the sixty-minute Installing timeout. Exactly C1's
	// failure shape. The console's own happy path built this, because its
	// dialog had no DNS field at all and the runbook's example omitted
	// dns too.
	//
	// Refused rather than defaulted to the gateway: a gateway that does
	// not forward DNS is a plausible house network, and guessing here
	// turns "you did not say" into the same silent halt one layer later.
	if len(s.Network.DNS) == 0 {
		return nil, nil, "", fmt.Errorf(
			"network DNS: at least one resolver is required; with none, the installer halts asking for a mirror it cannot resolve -- after partman has already wiped every named disk")
	}
	// DNS was the one interpolated value with no shape check: every other
	// field here is an address, a CIDR, a by-id path or an authorized_keys
	// line, each refused by construction rather than by blocklist. DNS had
	// only checkPreseedValue, which is a character blocklist -- it refuses
	// what breaks the two contexts, and passes anything else. A resolver
	// list is a list of IP addresses; nothing else belongs in one.
	for _, dns := range s.Network.DNS {
		if err := checkPreseedValue("network DNS", dns); err != nil {
			return nil, nil, "", err
		}
		if net.ParseIP(dns) == nil {
			return nil, nil, "", fmt.Errorf("network DNS %q is not an IP address", dns)
		}
	}

	recipe, err := PartmanRecipe(s.Layout)
	if err != nil {
		return nil, nil, "", err
	}

	return addr, net.IP(ipnet.Mask), recipe, nil
}

// RenderPreseed turns a Spec into a preseed.cfg.
//
// It refuses rather than emits when something is wrong, because the two ways
// this can go badly are silent: an image carrying secret material, and an
// installation that wipes a disk nobody named.
//
// runURL is where the installed-to machine fetches the preseed/run script
// (RenderRunScript) that re-runs netcfg. It is required and refused
// empty: without it every netcfg answer in the rendered file is inert and
// the machine comes up on a DHCP address under a DHCP name, which is the
// one failure mode this whole design cannot observe until after both disks
// are gone.
//
// beaconBase and token are where the machine reports progress. An empty
// beaconBase renders a preseed with no beacon lines at all -- the cold-start
// path (`frame bootstrap`) passes one, because nothing there reads a beacon.
// Rendering a base that goes nowhere instead would put a wget against a dead
// address in front of every install that path drives.
func RenderPreseed(s Spec, runURL, beaconBase, token string) (string, error) {
	addr, netmask, recipe, err := renderInputs(s)
	if err != nil {
		return "", err
	}

	if strings.TrimSpace(runURL) == "" {
		return "", fmt.Errorf("spec: no preseed/run URL, so netcfg would never re-run and the static network configuration would be inert")
	}
	if err := checkPreseedValue("preseed run URL", runURL); err != nil {
		return "", err
	}
	// The beacon base lands in the same two contexts every other
	// interpolated value does -- a preseed directive line, and a shell word
	// inside early_command and late_command. It gets the same guard.
	if err := ValidateBeaconBase(beaconBase); err != nil {
		return "", err
	}

	data := struct {
		IP, Netmask, Gateway, DNS, Hostname string
		SizeAssertion, Partman              string
		SSHPublicKey, UID, MarkerPath       string
		RunURL                              string
		BeaconEarly, BeaconPartman          string
		BeaconLate, BeaconHeartbeat         string
	}{
		IP:            addr.String(),
		Netmask:       netmask.String(),
		Gateway:       s.Network.Gateway,
		DNS:           strings.Join(s.Network.DNS, " "),
		Hostname:      s.Hostname,
		SizeAssertion: diskSizeAssertion(s.Layout),
		Partman:       recipe,
		SSHPublicKey:  strings.TrimSpace(s.SSHPublicKey),
		UID:           s.UID,
		MarkerPath:    markerPath,
		RunURL:        runURL,
		// Emitted after the size assertion above, never before: a machine
		// the assertion powers off must not have reported `early` first, or
		// a deliberate refusal becomes indistinguishable from a crash --
		// which is the failure this whole mechanism exists to separate.
		BeaconEarly:     BeaconSend(beaconBase, token, CheckpointEarly),
		BeaconPartman:   BeaconSend(beaconBase, token, CheckpointPartman),
		BeaconLate:      BeaconSend(beaconBase, token, CheckpointLate),
		BeaconHeartbeat: BeaconHeartbeat(beaconBase, token, CheckpointEarly),
	}

	var b strings.Builder
	if err := preseedTmpl.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// checkPreseedValue refuses what breaks the two contexts every interpolated
// value lands in: a preseed directive line, where a newline starts a new
// directive that runs as root, and a single-quoted shell word inside
// early_command and late_command, where a quote or a backslash ends the word
// and the rest becomes commands.
//
// It is one function applied to every field rather than a guard per field
// because a guard per field is exactly what failed here: SSHPublicKey was
// hardened four times while UID, Hostname, DNS and Disk.ByID -- same two
// contexts -- had none.
func checkPreseedValue(field, v string) error {
	if strings.ContainsAny(v, "\n\r") {
		return fmt.Errorf("%s: must not contain a newline; in a preseed a newline starts a new directive, which runs as root", field)
	}
	if strings.ContainsAny(v, "'\\") {
		return fmt.Errorf("%s: must not contain a quote or a backslash; this value is interpolated into a shell command in the preseed", field)
	}
	for _, r := range v {
		if r < 0x20 || r == 0x7f {
			return fmt.Errorf("%s: must not contain control characters", field)
		}
	}
	return nil
}

// checkPublicKeyOnly is the guard that keeps decision 3 true. The image is
// served over an unauthenticated HTTP path reachable by every notebook and
// sandbox on the platform, so anything secret in it is published.
//
// ssh.ParseAuthorizedKey is not that guard, and believing it was is the trap
// here. Handed a whole key file it finds the public line, ignores the private
// one, and returns no error -- measured, in both orders. So a Secret whose
// "id.pub" actually holds both halves, or a paste of `cat id_ed25519*`, parses
// cleanly and would be written into the image verbatim.
//
// What closes it is the single-line rule: one key, on one line, and nothing
// else in the value. checkPreseedValue is not used here, and its newline and
// metacharacter checks are kept duplicated on purpose: this function's
// messages are field-specific, and its tests assert those messages, which a
// shared, generic message would not let them do.
func checkPublicKeyOnly(key string) error {
	k := strings.TrimSpace(key)

	// A boundary this value crosses twice: into a generated preseed, and from
	// there onto a machine's disk. An ed25519 line is about 100 characters and
	// an RSA-4096 one about 750; 1024 admits both and refuses a paste of
	// something else entirely. Counted in characters, not bytes -- the message
	// says characters, and a byte count would be wrong for a key comment
	// containing non-ASCII text.
	if n := utf8.RuneCountInString(k); n == 0 || n > 1024 {
		return fmt.Errorf("ssh key: must be between 1 and 1024 characters, got %d", n)
	}

	// This branch is for the message, not for the hole -- the single-line rule
	// below already refuses every multi-line value. But "this is private key
	// material" is worth far more to whoever hit it than "must be a single
	// line", so its test asserts the message rather than merely the error.
	if strings.Contains(k, "PRIVATE KEY") {
		return fmt.Errorf("ssh key: this is private key material, which must never enter an installer image")
	}
	// This rule is not mainly about secrets -- the branch above catches PEM
	// armour, and a private key without armour is not a shape anyone produces
	// by accident. Its job is the other two: a second line is a second
	// authorized key, which grants someone else access to the machine being
	// built, and a newline inside the value truncates the shell command that
	// writes it in the preseed.
	if strings.ContainsAny(k, "\n\r") {
		return fmt.Errorf("ssh key: must be one key on one line; a second line is a second key, and a newline truncates the command that writes this value")
	}
	// The value is interpolated into a single-quoted shell word in the
	// preseed's late_command. A quote or a backslash in the comment field
	// breaks out of it, which turns a key comment into arbitrary commands run
	// as root on the machine being installed.
	if strings.ContainsAny(k, "'\\") {
		return fmt.Errorf("ssh key: must not contain a quote or a backslash; this value is interpolated into a shell command in the preseed")
	}

	_, comment, options, _, err := ssh.ParseAuthorizedKey([]byte(k))
	if err != nil {
		return fmt.Errorf("ssh key: not a usable authorized_keys line: %w", err)
	}
	// An authorized_keys options prefix (command=, no-pty, and the rest) is
	// exactly "something else in the value" -- measured, a key line carrying
	// command="curl ...|sh",no-pty parses cleanly, and the double quotes inside
	// it are inert in the single-quoted echo that writes this file, so the
	// metacharacter check above never sees it. It would run as Frame's own
	// login, "frame", who has NOPASSWD:ALL.
	if len(options) != 0 {
		return fmt.Errorf("ssh key: carries authorized_keys options (%q); this value must be a bare key", strings.Join(options, ","))
	}
	// The parser's trailing remainder is not the check it looks like: it holds
	// unconsumed *lines*, never unconsumed words, and the single-line rule
	// above already refuses every multi-line value -- so inspecting it would
	// be dead code behind a passing test. Two keys on one line land somewhere
	// else entirely: the parser takes the first and folds the whole second key
	// into the first one's comment field. Measured. So the comment is what has
	// to be looked at, and the exact test is whether it parses as a key on its
	// own.
	if _, _, _, _, err := ssh.ParseAuthorizedKey([]byte(strings.TrimSpace(comment))); err == nil {
		return fmt.Errorf("ssh key: more than one key in this value; the second is hidden in the first one's comment field")
	}
	return nil
}
