apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: frame-base-worker
  namespace: sidero-system
spec:
  qualifiers:
    cpu:
      - manufacturer: Intel
      - manufacturer: AMD
  configPatches:
    - op: add
      path: /machine/nodeLabels/frame.plume-labs.io~1service-class
      value: "MEDIUM"
    - op: add
      path: /machine/nodeLabels/frame.plume-labs.io~1server-class
      value: "base-worker"
  environmentRef:
    name: frame-default
