apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: frame-base-worker
  namespace: sidero-system
spec:
  qualifiers:
    cpu:
      - manufacturer: Intel
      - manufacturer: AMD
  configPatches:
    - op: add
      path: /machine/nodeLabels
      value:
        frame.plume-labs.io/service-class: "MEDIUM"
        frame.plume-labs.io/server-class: "base-worker"
  environmentRef:
    name: frame-default
