apiVersion: metal.sidero.dev/v1alpha2
kind: ServerClass
metadata:
  name: frame-rdma-worker
  namespace: sidero-system
spec:
  qualifiers:
    pciAddresses:
      - "15b3:" # Mellanox/NVIDIA networking
  configPatches:
    - op: add
      path: /machine/nodeLabels/rdma
      value: "true"
    - op: add
      path: /machine/nodeLabels/frame.plume-labs.io~1service-class
      value: "HIGH"
    - op: add
      path: /machine/nodeLabels/frame.plume-labs.io~1server-class
      value: "rdma-worker"
  environmentRef:
    name: frame-default
